wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
beta1:
  value: 0.9
beta2:
  value: 0.999
beta_rms:
  value: 0.9
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32
init_type:
  value: xavier
learning_rate:
  value: 0.001
loss_func:
  value: cross_entropy
momentum:
  value: 0.9
num_hidden_layers:
  value: 5
optimizer:
  value: momentum
weight_decay:
  value: 0.5
