_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.6
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.6
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
batch_size:
    value: 64
beta_rms:
    value: 0.9
beta1:
    value: 0.9
beta2:
    value: 0.999
epochs:
    value: 10
epsilon:
    value: 1e-08
layers:
    value:
        - 784
        - 128
        - 64
        - 10
learning_rate:
    value: 0.001
momentum:
    value: 0.9
optimizer:
    value: nadam
