wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
beta1:
  value: 0.9
beta2:
  value: 0.999
beta_rms:
  value: 0.9
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
init_type:
  value: xavier
learning_rate:
  value: 0.001
loss_func:
  value: cross_entropy
momentum:
  value: 0.9
num_hidden_layers:
  value: 4
optimizer:
  value: adam
weight_decay:
  value: 0.0005
