wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
beta1:
  value: 0.9
beta2:
  value: 0.999
beta_rms:
  value: 0.9
epochs:
  value: 50
epsilon:
  value: 1.0e-08
hidden_size:
  value: 256
init_type:
  value: random
learning_rate:
  value: 0.0003
loss_func:
  value: cross_entropy
momentum:
  value: 0.8
num_hidden_layers:
  value: 4
optimizer:
  value: nesterov
weight_decay:
  value: 1.0e-05
